# 用于浏览器标签的图标
# Icon for browser tab
favicon: /img/docs.png

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: /img/docs.png

# 默认背景图
banner_img: /img/default.jpg

# 启用html缓存，默认关闭，除非页面经常不更新
html_cache_enable: false

# 主题 light | dark
dark_mode: dark

# 头像
avatar: /img/avatar.png
