favicon: /img/docs.png
apple_touch_icon: /img/docs.png
tab_title_separator: " - "
force_https: false
code:
  copy_btn: true
  language:
    enable: true
    default: TEXT
  highlight:
    enable: true
    line_number: true
    lib: prismjs
    highlightjs:
      style: github gist
      style_dark: dark
    prismjs:
      style: default
      style_dark: tomorrow night
      preprocess: true
fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: _
    loop: false
    scope: []
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left
    visible: hover
    icon: ""
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    options:
      showSpinner: false
      trickleSpeed: 100
dark_mode:
  enable: true
  default: auto
color:
  body_bg_color: "#fff"
  body_bg_color_dark: "#000"
  navbar_bg_color: "#000"
  navbar_bg_color_dark: "#000"
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  subtitle_color: "#fff"
  subtitle_color_dark: "#d0d0d0"
  text_color: "#000"
  text_color_dark: "#dbdbdb"
  sec_text_color: "#000"
  sec_text_color_dark: "#e6e6e6"
  board_color: "#fff"
  board_color_dark: "#252d38"
  post_text_color: "#000"
  post_text_color_dark: "#c8c8c8"
  post_heading_color: "#000"
  post_heading_color_dark: "#d0d0d0"
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#3d424b"
  line_color: "#eaecef"
  line_color_dark: "#435266"
  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
  button_bg_color: transparent
  button_bg_color_dark: transparent
  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"
font:
  font_size: 16px
  font_family: null
  letter_spacing: 0.02em
  code_font_size: 85%
custom_js: null
custom_css: null
custom_head:
  - <meta http-equiv="Cache-Control" content="no-cache,no-store,must-revalidate">
  - <meta http-equiv="Pragma" content="no-cache">
  - <meta http-equiv="Expires" content="0">
web_analytics:
  enable: true
  follow_dnt: true
  baidu: null
  google: null
  gtag: null
  tencent:
    sid: null
    cid: null
  woyaola: null
  cnzz: null
  leancloud:
    app_id: null
    app_key: null
    server_url: null
    path: window.location.pathname
    ignore_local: false
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2
iconfont: //at.alicdn.com/t/font_1736178_lbnruvf0jn.css
navbar:
  blog_title: LNote
  ground_glass:
    enable: false
    px: 3
    alpha: 0.7
  menu:
    - key: home
      link: /
      icon: iconfont icon-home-fill
    - key: archive
      link: /archives/
      icon: iconfont icon-archive-fill
    - key: category
      link: /categories/
      icon: iconfont icon-category-fill
    - key: tag
      link: /tags/
      icon: iconfont icon-tags-fill
    - key: about
      link: /about/
      icon: iconfont icon-user-fill
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true
banner:
  parallax: true
  width_height_ratio: 1
scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true
scroll_top_arrow:
  enable: true
open_graph:
  enable: true
  twitter_card: summary_large_image
  twitter_id: null
  twitter_site: null
  google_plus: null
  fb_admins: null
  fb_app_id: null
footer:
  content: null
  statistics:
    enable: false
    source: busuanzi
  beian:
    enable: false
    icp_text: 京ICP证123456号
    police_text: 京公网安备12345678号
    police_code: 12345678
    police_icon: /img/police_beian.png
index:
  banner_img: /img/default.jpg
  banner_img_height: 100
  banner_mask_alpha: 0.3
  slogan:
    enable: true
    text: 记录、整理、分析、吸收经验
    api:
      enable: false
      url: ""
      method: GET
      headers: {}
      keys: []
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: true
  post_sticky:
    enable: true
    icon: iconfont icon-top
post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  default_index_img: null
  meta:
    author:
      enable: false
    date:
      enable: true
      format: LLLL
    wordcount:
      enable: true
    min2read:
      enable: true
      awl: 2
      wpm: 60
    views:
      enable: true
      source: busuanzi
  updated:
    enable: true
    date_format: LLLL
    relative: false
    note_class: info
  category_bar:
    enable: true
    specific: true
    placement: left
    post_order_by: title
    post_limit: 0
  toc:
    enable: true
    placement: right
    headingSelector: h1,h2,h3,h4,h5,h6
    collapseDepth: 0
  copyright:
    enable: true
    license: BY
    author:
      enable: true
    post_date:
      enable: true
      format: LL
    update_date:
      enable: true
      format: LL
  prev_next:
    enable: true
  image_caption:
    enable: true
  image_zoom:
    enable: true
    img_url_replace:
      - ""
      - ""
  footnote:
    enable: true
    header: ""
  math:
    enable: false
    specific: false
    engine: mathjax
  mermaid:
    enable: true
    specific: true
    options:
      theme: dark
  comments:
    enable: false
    type: disqus
utterances:
  repo: null
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark
disqus:
  shortname: null
  disqusjs: false
  apikey: null
gitalk:
  clientID: null
  clientSecret: null
  repo: null
  owner: null
  admin:
    - name
  language: zh-CN
  labels:
    - Gitalk
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
valine:
  appId: null
  appKey: null
  path: window.location.pathname
  placeholder: null
  avatar: retro
  meta:
    - nick
    - mail
    - link
  requiredFields: []
  pageSize: 10
  lang: zh-CN
  highlight: false
  recordIP: false
  serverURLs: ""
  emojiCDN: null
  emojiMaps: null
  enableQQ: false
waline:
  serverURL: ""
  path: window.location.pathname
  meta:
    - nick
    - mail
    - link
  requiredMeta:
    - nick
  lang: zh-CN
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
  dark: html[data-user-color-scheme="dark"]
  wordLimit: 0
  pageSize: 10
changyan:
  appid: ""
  appkey: ""
livere:
  uid: ""
remark42:
  host: null
  site_id: null
  max_shown_comments: 10
  locale: zh
  components:
    - embed
twikoo:
  envId: null
  region: ap-shanghai
  path: window.location.pathname
cusdis:
  host: null
  app_id: null
  lang: zh-cn
giscus:
  repo: null
  repo-id: null
  category: null
  category-id: null
  theme-light: light
  theme-dark: dark
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  input-position: top
  lang: zh-CN
archive:
  banner_img: /img/default.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
category:
  enable: true
  banner_img: /img/default.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  order_by: -length
  collapse_depth: 0
  post_order_by: -date
  post_limit: 10
tag:
  enable: true
  banner_img: /img/default.jpg
  banner_img_height: 80
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"
about:
  enable: true
  banner_img: /img/default.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: me
  intro: myname
  icons:
    - class: iconfont icon-wechat-fill
      qrcode: /img/avatar.png
      tip: wechat
    - class: iconfont icon-qq-fill
      qrcode: /img/avatar.png
      tip: qq
page:
  banner_img: /img/default.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
page404:
  enable: true
  banner_img: /img/default.jpg
  banner_img_height: 85
  banner_mask_alpha: 0.3
  redirect_delay: 5000
links:
  enable: false
  banner_img: /img/default.jpg
  banner_img_height: 60
  banner_mask_alpha: 0.3
  onerror_avatar: /img/avatar.png
  custom:
    enable: false
    content: <hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid
      主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>
  comments:
    enable: false
    type: disqus
static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://lib.baomitu.com/anchor-js/4.3.1/
  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/
  jquery: https://lib.baomitu.com/jquery/3.6.0/
  bootstrap: //cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.3.1/
  prismjs: https://lib.baomitu.com/prism/1.29.0/
  tocbot: https://lib.baomitu.com/tocbot/4.18.2/
  typed: https://lib.baomitu.com/typed.js/2.0.12/
  fancybox: https://lib.baomitu.com/fancybox/3.5.7/
  nprogress: https://lib.baomitu.com/nprogress/0.2.0/
  mathjax: https://lib.baomitu.com/mathjax/3.2.2/
  katex: https://lib.baomitu.com/KaTeX/0.16.2/
  busuanzi: //cdn.bootcdn.net/ajax/libs/busuanzi/2.3.0/bsz.pure.mini.min.js
  finicounter: //finicounter.eu.org/finicounter.js
  clipboard: https://lib.baomitu.com/clipboard.js/2.0.11/
  mermaid: //cdn.bootcdn.net/ajax/libs/mermaid/10.4.0/
  valine: https://lib.baomitu.com/valine/1.5.1/
  waline: https://lib.baomitu.com/waline/2.14.1/
  gitalk: https://lib.baomitu.com/gitalk/1.8.0/
  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/
  twikoo: https://lib.baomitu.com/twikoo/1.6.8/
  hint: https://lib.baomitu.com/hint.css/2.7.0/
